name: Deploy to InfinityFree

# Trigger deployment on push to main branch and manual dispatch
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to InfinityFree
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚀 Checkout code
      uses: actions/checkout@v4
      
    - name: 🐘 Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mysqli, curl, fileinfo, gd
        tools: composer
        
    - name: 📦 Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
          
    - name: 🔧 Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader --no-interaction
      
    - name: 📝 Create deployment package
      run: |
        # Create necessary directories for deployment
        mkdir -p deploy-package/attachments
        mkdir -p deploy-package/pdf_exports
        
        # Copy application files with custom exclusions (not using .gitignore)
        rsync -av \
          --exclude='.git/' \
          --exclude='.github/' \
          --exclude='deploy-package/' \
          --exclude='README.md' \
          --exclude='PDF_FEATURE_README.md' \
          --exclude='pdf_exports/*' \
          --exclude='attachments/*' \
          --include='pdf_exports/index.php' \
          --include='attachments/.htaccess' \
          ./ deploy-package/
          
        # Ensure vendor directory and composer files are included
        if [ -d "vendor" ]; then
          echo "✅ Vendor directory found and included in deployment"
        else
          echo "⚠️  Vendor directory not found - running composer install"
          composer install --no-dev --optimize-autoloader --no-interaction
        fi
          
        # Create .htaccess for security
        echo "Options -Indexes" > deploy-package/attachments/.htaccess
        echo "Options -Indexes" > deploy-package/pdf_exports/.htaccess
        
        # Create index.php files for security
        echo "<?php header('Location: ../index.php'); exit(); ?>" > deploy-package/attachments/index.php
        echo "<?php header('Location: ../index.php'); exit(); ?>" > deploy-package/pdf_exports/index.php
        
        # Create sample config file (user will need to customize)
        cp config.php deploy-package/config.sample.php || echo "No config.php found, creating sample..."
        
        # Verify essential files are included
        echo "🔍 Verifying deployment package contents:"
        echo "   • composer.json: $([ -f deploy-package/composer.json ] && echo "✅ Found" || echo "❌ Missing")"
        echo "   • composer.lock: $([ -f deploy-package/composer.lock ] && echo "✅ Found" || echo "❌ Missing")"
        echo "   • vendor/autoload.php: $([ -f deploy-package/vendor/autoload.php ] && echo "✅ Found" || echo "❌ Missing")"
        echo "   • TCPDF: $([ -f deploy-package/vendor/tecnickcom/tcpdf/tcpdf.php ] && echo "✅ Found" || echo "❌ Missing")"
        echo "   • functions.php: $([ -f deploy-package/functions.php ] && echo "✅ Found" || echo "❌ Missing")"
        echo ""
        
    - name: 🌐 Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deploy-package/
        server-dir: /htdocs/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/tests/**
          **/*.md
          config.php
        
    - name: 🎉 Deployment Success
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🔗 Your memo system should now be available at your InfinityFree domain"
        echo "📦 Included in deployment:"
        echo "   • All PHP application files"
        echo "   • Composer dependencies (vendor/ directory)"
        echo "   • TCPDF library for PDF generation"
        echo "   • Security files (.htaccess)"
        echo ""
        echo "⚠️  Don't forget to:"
        echo "   1. Create and configure config.php on the server"
        echo "   2. Import the database using the provided db.sql file"
        echo "   3. Set proper permissions for attachments/ and pdf_exports/ directories"
        echo "   4. Verify that PHP extensions (mysqli, gd, mbstring) are enabled"
